version: '3.7'

services:
  frontend:
    build:
      context: ./
      args:
        HASHED_NAMES_URL: https://run.mocky.io/v3/67ba6e24-5e81-4f6d-8d4a-da41961dc044/
        ENCODE_URL: https://run.mocky.io/v3/a5a20cf3-d602-42ca-b591-776a7d51a0ba
    ports:
      - "2000:80"